export const nftData = [
  {
    id: 0,
    name: 'Blue Jewel',
    code: '#2652',
    image: 'https://upload.wikimedia.org/wikipedia/en/2/26/Paul_Rudish_Mickey_Mouse.png',
    price: 0.043,
    unit: 'APT',
    effect: '10% Speed / 0.3% Size',
  },
  {
    id: 1,
    name: 'Blue Jewel',
    code: '#4444',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Mickey_Mouse_head_and_ears.svg/440px-Mickey_Mouse_head_and_ears.svg.png',
    price: 0.043,
    unit: 'APT',
    effect: '10% Speed / 0.3% Size',
  },
  {
    id: 2,
    name: 'Blue Jewel',
    code: '#4444',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Walt_disney_portrait.jpg/440px-Walt_disney_portrait.jpg',
    price: 0.043,
    unit: 'APT',
    effect: '10% Speed / 0.3% Size',
  },
  {
    id: 3,
    name: 'Blue Jewel',
    code: '#4444',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Mickey_Mouse_head_and_ears.svg/440px-Mickey_Mouse_head_and_ears.svg.png',
    price: 0.043,
    unit: 'APT',
    effect: '10% Speed / 0.3% Size',
  },
  {
    id: 4,
    name: 'Blue Jewel',
    code: '#4444',
    image: 'https://upload.wikimedia.org/wikipedia/en/2/26/Paul_Rudish_Mickey_Mouse.png',
    price: 0.043,
    unit: 'APT',
    effect: '10% Speed / 0.3% Size',
  }
];
